const card = [
  {
    day: 1,

    nihongo1: "ゆめ",
    nihongo2: "しんじる",
    nihongo3: "つよい",
    nihongo4: "かんけい",
    nihongo5: "あたらしい",
    nihongo6: "せいかい",
    nihongo7: "しゃかい じん",
    nihongo8: "せんこう",
    nihongo9: "たいへん",
    nihongo10: "わら",

    english1: "dream",
    english2: "believe",
    english3: "strong",
    english4: "relationship",
    english5: "new",
    english6: "correct",
    english7: "working person",
    english8: "major",
    english9: "tough",
    english10: "LOL",
  },
  {
    day: 2,

    nihongo1: "れんしゅう",
    nihongo2: "まちがい",
    nihongo3: "かんがえる",
    nihongo4: "わすれる",
    nihongo5: "かんたん",
    nihongo6: "テスト を しましょう",
    nihongo7: "ちょうし は どう？",
    nihongo8: "じゅうよう",
    nihongo9: "あってる",
    nihongo10: "かいわ",

    english1: "practice",
    english2: "wrong",
    english3: "to think",
    english4: "to forget",
    english5: "easy / simple",
    english6: "let's do a test",
    english7: "how are you doing?",
    english8: "important",
    english9: "correct",
    english10: "conversation",
  },
  {
    day: 3,

    nihongo1: "じょうず",
    nihongo2: "しつもん",
    nihongo3: "しゃしん",
    nihongo4: "えらぶ",
    nihongo5: "へや",
    nihongo6: "そうじ を する",
    nihongo7: "けんさく",
    nihongo8: "ひみつ",
    nihongo9: "へんしん",
    nihongo10: "えがお",

    english1: "skilled",
    english2: "question",
    english3: "photograph",
    english4: "to choose",
    english5: "room",
    english6: "to clean",
    english7: "to search (internet)",
    english8: "secret",
    english9: "reply",
    english10: "smile",
  },
  {
    day: 4,

    nihongo1: "いくら",
    nihongo2: "なつかしい",
    nihongo3: "めんどくさい",
    nihongo4: "しかたない",
    nihongo5: "ぜんぶ",
    nihongo6: "ねつ",
    nihongo7: "おすすめ",
    nihongo8: "やくそく",
    nihongo9: "きおく",
    nihongo10: "しかる",

    english1: "how much?",
    english2: "nostalgic",
    english3: "troublesome",
    english4: "'it can't be helped'",
    english5: "all / everything",
    english6: "fever",
    english7: "recommendations",
    english8: "promise",
    english9: "memories",
    english10: "to scold",
  },
  {
    day: 5,

    nihongo1: "もんだい",
    nihongo2: "しんぱい",
    nihongo3: "もちろん",
    nihongo4: "おなじ",
    nihongo5: "たとえば",
    nihongo6: "きもい",
    nihongo7: "しょうじき",
    nihongo8: "まなぶ",
    nihongo9: "やね",
    nihongo10: "さき",

    english1: "problem",
    english2: "worry",
    english3: "of course",
    english4: "same",
    english5: "for example",
    english6: "cringe",
    english7: "honestly / actually",
    english8: "to learn",
    english9: "roof",
    english10: "ahead (saki ni tabete kudasai)",
  },
  {
    day: 6,

    nihongo1: "もう いっかい",
    nihongo2: "おんがく",
    nihongo3: "まで",
    nihongo4: "やすみ",
    nihongo5: "すいそく",
    nihongo6: "くるま",
    nihongo7: "かぞく",
    nihongo8: "こんど",
    nihongo9: "つめたい",
    nihongo10: "きにしないで",

    english1: "1 more time",
    english2: "music",
    english3: "until",
    english4: "break / day off",
    english5: "guess",
    english6: "car",
    english7: "family",
    english8: "next time",
    english9: "cold",
    english10: "don't mind it",
  },
  {
    day: 7,

    nihongo1: "あそぶ",
    nihongo2: "におい",
    nihongo3: "あじ",
    nihongo4: "もと",
    nihongo5: "おえる",
    nihongo6: "しゅくだい",
    nihongo7: "すぎる",
    nihongo8: "でんき",
    nihongo9: "かぜ",
    nihongo10: "なまける",

    english1: "to play",
    english2: "odor / smell",
    english3: "taste",
    english4: "the origin",
    english5: "to finish",
    english6: "homework",
    english7: "too much (excessive)",
    english8: "electricity",
    english9: "cold (sakit)",
    english10: "to be lazy",
  },
  {
    day: 8,

    nihongo1: "ちゃんと",
    nihongo2: "おかね",
    nihongo3: "なかま",
    nihongo4: "さいこう",
    nihongo5: "ぜん ぜん",
    nihongo6: "そう",
    nihongo7: "おみやげ",
    nihongo8: "あける",
    nihongo9: "しめる",
    nihongo10: "びょうき",

    english1: "properly",
    english2: "money",
    english3: "friend / comrade",
    english4: "the best",
    english5: "not at all",
    english6: "it looks ...(adjective)",
    english7: "souvenir",
    english8: "to open",
    english9: "to close",
    english10: "sickness / disease",
  },
  {
    day: 9,

    nihongo1: "つれて　いく",
    nihongo2: "いれる",
    nihongo3: "だす",
    nihongo4: "つもり",
    nihongo5: "ほとんど",
    nihongo6: "ぐうぜん",
    nihongo7: "じゃま",
    nihongo8: "しんりん",
    nihongo9: "どくしん",
    nihongo10: "ひとめ",

    english1: "to bring someone",
    english2: "to put something inside",
    english3: "to take out/to put out",
    english4: "intention",
    english5: "almost",
    english6: "coincidence",
    english7: "disturb",
    english8: "forest",
    english9: "single / unmarried",
    english10: "glimpse / glance",
  },

  {
    day: 10,

    nihongo1: "つくえ",
    nihongo2: "いす",
    nihongo3: "しゅみ",
    nihongo4: "かさ",
    nihongo5: "やわらかい",
    nihongo6: "みにくい",
    nihongo7: "おこってる",
    nihongo8: "てんき",
    nihongo9: "ひくい",
    nihongo10: "きじ",

    english1: "desk",
    english2: "chair",
    english3: "hobby",
    english4: "umbrella",
    english5: "soft",
    english6: "ugly",
    english7: "to get angry",
    english8: "weather",
    english9: "low",
    english10: "article",
  },
  {
    day: 11,

    nihongo1: "くつ",
    nihongo2: "にんじん",
    nihongo3: "じゃがいも",
    nihongo4: "おと",
    nihongo5: "きょうだい",
    nihongo6: "だまる",
    nihongo7: "とけい",
    nihongo8: "にる",
    nihongo9: "ぶ",
    nihongo10: "おかし",

    english1: "shoes",
    english2: "carrot",
    english3: "potato",
    english4: "sound",
    english5: "sibling",
    english6: "to shut up",
    english7: "clock",
    english8: "to resemble someone",
    english9: "department",
    english10: "sweets / snacks",
  },
  {
    day: 12,

    nihongo1: "おとな",
    nihongo2: "ひこうき",
    nihongo3: "のる",
    nihongo4: "くち",
    nihongo5: "かぜ",
    nihongo6: "やちん",
    nihongo7: "ふとりました",
    nihongo8: "かす",
    nihongo9: "とる",
    nihongo10: "ようじ",

    english1: "adult",
    english2: "airplane",
    english3: "to ride / to get on",
    english4: "mouth",
    english5: "wind",
    english6: "rent",
    english7: "got fat",
    english8: "to lend",
    english9: "to take (to take a photo)",
    english10: "errand",
  },
  {
    day: 13,

    nihongo1: "ところ",
    nihongo2: "ぶんか",
    nihongo3: "あう",
    nihongo4: "わかい",
    nihongo5: "みせる",
    nihongo6: "たしかに",
    nihongo7: "どう　おもいますか",
    nihongo8: "まいあさ",
    nihongo9: "きんちょう　する",
    nihongo10: "じゅぎょう",

    english1: "place",
    english2: "culture",
    english3: "to meet",
    english4: "young",
    english5: "to show",
    english6: "indeed",
    english7: "what do you think?",
    english8: "every morning",
    english9: "to be nervous",
    english10: "class",
  },
  {
    day: 14,

    nihongo1: "かいちょう",
    nihongo2: "いろ　いろ",
    nihongo3: "じんぶｎ",
    nihongo4: "さいご",
    nihongo5: "かいぜん",
    nihongo6: "きぶん",
    nihongo7: "きゅうけい",
    nihongo8: "きっぷ",
    nihongo9: "のぼる",
    nihongo10: "きゃく",

    english1: "chairman / head",
    english2: "various",
    english3: "myself / yourself",
    english4: "last",
    english5: "improvement",
    english6: "feeling",
    english7: "rest",
    english8: "ticket",
    english9: "to climb",
    english10: "customer",
  },
  {
    day: 15,

    nihongo1: "きょうみ",
    nihongo2: "けっこん",
    nihongo3: "りこん",
    nihongo4: "とめる",
    nihongo5: "むり",
    nihongo6: "おく",
    nihongo7: "おりる",
    nihongo8: "たのむ",
    nihongo9: "とぶ",
    nihongo10: "ひく",

    english1: "interest in something",
    english2: "marriage",
    english3: "divorce",
    english4: "to stop",
    english5: "impossible",
    english6: "to put",
    english7: "to get off",
    english8: "to ask",
    english9: "to jump / to fly",
    english10: "to play an instrument",
  },
  {
    day: 16,

    nihongo1: "れきし",
    nihongo2: "げんきん",
    nihongo3: "はらう",
    nihongo4: "うつかしい",
    nihongo5: "たてもの",
    nihongo6: "たぶん",
    nihongo7: "おちる",
    nihongo8: "つづく",
    nihongo9: "こえ",
    nihongo10: "かわる",

    english1: "history",
    english2: "cash",
    english3: "to pay",
    english4: "pretty",
    english5: "building",
    english6: "maybe",
    english7: "to fall down",
    english8: "to continue",
    english9: "voice",
    english10: "to change",
  },
  {
    day: 17,

    nihongo1: "かいてき",
    nihongo2: "いみ",
    nihongo3: "ひつよう",
    nihongo4: "うち",
    nihongo5: "あこがれる",
    nihongo6: "こたえる",
    nihongo7: "しんちょう",
    nihongo8: "ちゅうい",
    nihongo9: "こんかい",
    nihongo10: "てがみ",

    english1: "comfortable",
    english2: "meaning",
    english3: "necessary",
    english4: "home / house",
    english5: "to admire",
    english6: "to answer",
    english7: "height",
    english8: "attention",
    english9: "this time",
    english10: "letter",
  },
  {
    day: 18,

    nihongo1: "ほんき",
    nihongo2: "だけ",
    nihongo3: "かかる",
    nihongo4: "はたらく",
    nihongo5: "くらい",
    nihongo6: "きっさてん",
    nihongo7: "ゆれい",
    nihongo8: "やせる",
    nihongo9: "ふとる",
    nihongo10: "こわい",

    english1: "seriously",
    english2: "only",
    english3: "to cost / to take",
    english4: "to work",
    english5: "dark",
    english6: "coffee shop",
    english7: "ghost",
    english8: "to lose weight",
    english9: "to gain weight",
    english10: "scared",
  },
  {
    day: 19,

    nihongo1: "ざんねん",
    nihongo2: "とき",
    nihongo3: "はれ",
    nihongo4: "うんどう",
    nihongo5: "へび",
    nihongo6: "なる",
    nihongo7: "はやる",
    nihongo8: "かむ",
    nihongo9: "かぞえる",
    nihongo10: "つきあう",

    english1: "unfotrunate / too bad",
    english2: "when (atsui toki -> when its hot)",
    english3: "sunny",
    english4: "exercise",
    english5: "snake",
    english6: "to become",
    english7: "to be popular",
    english8: "to bite / to chew",
    english9: "to count",
    english10: "to date <3",
  },
  {
    day: 20,

    nihongo1: "しぜんあ",
    nihongo2: "ゆっくり",
    nihongo3: "あきらめる",
    nihongo4: "ねむい",
    nihongo5: "しゅうちゅう",
    nihongo6: "たたかう",
    nihongo7: "みつける",
    nihongo8: "あつまる",
    nihongo9: "あげる",
    nihongo10: "くれる",

    english1: "natural",
    english2: "slowly",
    english3: "to give up",
    english4: "sleepy",
    english5: "concentration",
    english6: "to fight",
    english7: "to find",
    english8: "to gather / to assemble",
    english9: "to give (give -> other person)",
    english10: "to give (you <- someone give)",
  },
  {
    day: 21,

    nihongo1: "もくひょう",
    nihongo2: "うごく",
    nihongo3: "りゅうちょう",
    nihongo4: "なく",
    nihongo5: "せつめい",
    nihongo6: "だいじ",
    nihongo7: "くりかえす",
    nihongo8: "ゆるす",
    nihongo9: "うそつき",
    nihongo10: "まくら",

    english1: "goal / objective",
    english2: "to move",
    english3: "fluent",
    english4: "to cry",
    english5: "explanation",
    english6: "important",
    english7: "to repeat",
    english8: "to forgive",
    english9: "liar",
    english10: "pillow",
  },

  {
    day: 22,

    nihongo1: "みせ",
    nihongo2: "ていねい",
    nihongo3: "かゆい",
    nihongo4: "あせる",
    nihongo5: "あきる",
    nihongo6: "すすむ",
    nihongo7: "かりる",
    nihongo8: "しあわせ",
    nihongo9: "へた",
    nihongo10: "あぶない",

    english1: "store / shop",
    english2: "polite",
    english3: "itchi",
    english4: "to rush",
    english5: "to lose interest / tired of",
    english6: "to advance / move forward",
    english7: "to rent / to borrow",
    english8: "happy / happiness in life",
    english9: "unskilled",
    english10: "dangerous",
  },
  {
    day: 23,

    nihongo1: "ひきわけ",
    nihongo2: "じんせい",
    nihongo3: "つくる",
    nihongo4: "かんしゃ",
    nihongo5: "りょうこう",
    nihongo6: "そろ　そろ",
    nihongo7: "まど",
    nihongo8: "きづく",
    nihongo9: "きおつける",
    nihongo10: "やま",

    english1: "draw / no win or lose",
    english2: "human life",
    english3: "to make",
    english4: "appreciation / gratitude",
    english5: "travel",
    english6: "anytime soon",
    english7: "window",
    english8: "to notice",
    english9: "to be careful",
    english10: "mountain",
  },
  {
    day: 24,

    nihongo1: "ごみ",
    nihongo2: "つき",
    nihongo3: "すてる",
    nihongo4: "あい",
    nihongo5: "たいよう",
    nihongo6: "けっきょうく",
    nihongo7: "かもしれない",
    nihongo8: "かべ",
    nihongo9: "しんぶん",
    nihongo10: "じしょ",

    english1: "garbage",
    english2: "moon",
    english3: "to throw away",
    english4: "love",
    english5: "sun",
    english6: "in the end / after all",
    english7: "it might",
    english8: "wall",
    english9: "newspaper",
    english10: "dictionary",
  },
  {
    day: 25,

    nihongo1: "ほしい",
    nihongo2: "けいたい",
    nihongo3: "にわ",
    nihongo4: "き",
    nihongo5: "かんこう",
    nihongo6: "ぼにんげん",
    nihongo7: "ども",
    nihongo8: "きびしい",
    nihongo9: "こちら　こそ",
    nihongo10: "けいっこう",

    english1: "want",
    english2: "cellphone",
    english3: "garden",
    english4: "tree",
    english5: "sight seeing",
    english6: "stick figure",
    english7: "thanks",
    english8: "strict",
    english9: "likewise",
    english10: "enough",
  },
  {
    day: 26,

    nihongo1: "うみ",
    nihongo2: "ちょうせん",
    nihongo3: "くに",
    nihongo4: "あんぜｎ",
    nihongo5: "おまつり",
    nihongo6: "はつおん",
    nihongo7: "あんしん",
    nihongo8: "あやまる",
    nihongo9: "じてんしゃ",
    nihongo10: "いしゃ",

    english1: "sea",
    english2: "challenge",
    english3: "country",
    english4: "safe",
    english5: "festival",
    english6: "pronunciation",
    english7: "relief / peace of mind",
    english8: "to apologize",
    english9: "bike",
    english10: "doctor",
  },
  {
    day: 27,

    nihongo1: "お　だいじ　に",
    nihongo2: "さいてい",
    nihongo3: "つかう",
    nihongo4: "くすり",
    nihongo5: "ほし",
    nihongo6: "れいぞうこ",
    nihongo7: "せんたくき",
    nihongo8: "かぐ",
    nihongo9: "ふね",
    nihongo10: "でぐち",

    english1: "get well soon",
    english2: "the worst",
    english3: "to use",
    english4: "medicine",
    english5: "start",
    english6: "refrigerator",
    english7: "wasing machine",
    english8: "furniture",
    english9: "boat",
    english10: "exit",
  },
  {
    day: 28,

    nihongo1: "かいしゃ",
    nihongo2: "えき",
    nihongo3: "かぎ",
    nihongo4: "ぎゅうにゅう",
    nihongo5: "だいどころ",
    nihongo6: "さんぽ",
    nihongo7: "めずらしい",
    nihongo8: "うらやましい",
    nihongo9: "へんか",
    nihongo10: "かいしゃいん",

    english1: "company",
    english2: "station",
    english3: "key",
    english4: "milk",
    english5: "kitchen",
    english6: "stroll / walk around",
    english7: "rare",
    english8: "jealous / envy",
    english9: "change (physical appearance)",
    english10: "company employee",
  },
  {
    day: 29,

    nihongo1: "しょくじ",
    nihongo2: "やすむ",
    nihongo3: "まち",
    nihongo4: "びょういん",
    nihongo5: "はじめて",
    nihongo6: "りゆう",
    nihongo7: "かいがい",
    nihongo8: "かいぎ",
    nihongo9: "しょくどう",
    nihongo10: "うけつけ",

    english1: "meal",
    english2: "to rest",
    english3: "city / town",
    english4: "hospital",
    english5: "first time",
    english6: "reason",
    english7: "overseas",
    english8: "meeting",
    english9: "cafeteria",
    english10: "reception desk",
  },
  {
    day: 30,

    nihongo1: "ことば",
    nihongo2: "ふくざつ",
    nihongo3: "てんきｎ",
    nihongo4: "のど",
    nihongo5: "やる",
    nihongo6: "じどおはんばいき",
    nihongo7: "しゅくじつ",
    nihongo8: "しゅうまつ",
    nihongo9: "スパ",
    nihongo10: "ぎんこう",

    english1: "word",
    english2: "complicated / complex",
    english3: "transfer",
    english4: "throat",
    english5: "to do (LETS DOO IT!!)",
    english6: "vending machine",
    english7: "holiday",
    english8: "weekend",
    english9: "supermarket",
    english10: "bank",
  },
  {
    day: 31,

    nihongo1: "すぐ",
    nihongo2: "すく",
    nihongo3: "さげる",
    nihongo4: "がまん　する",
    nihongo5: "そら",
    nihongo6: "ふべん",
    nihongo7: "デパト",
    nihongo8: "ゆうびんきょうく",
    nihongo9: "としょかん",
    nihongo10: "びじゅつかん",

    english1: "soon",
    english2: "to be empty / hungry",
    english3: "to lower",
    english4: "to endure / to tolerate",
    english5: "sky",
    english6: "inconvenient",
    english7: "department store",
    english8: "post office",
    english9: "library",
    english10: "art museum",
  },
  {
    day: 32,

    nihongo1: "みもつ",
    nihongo2: "でかれる",
    nihongo3: "ずぼん",
    nihongo4: "もつ",
    nihongo5: "はく",
    nihongo6: "じゅんちょう",
    nihongo7: "こうえん",
    nihongo8: "せき",
    nihongo9: "えあこん",
    nihongo10: "でんしゃ",

    english1: "luggage",
    english2: "to go out (for work, shopping, etc)",
    english3: "pants",
    english4: "to have / to hold / to own",
    english5: "to put on (lower body clothing)",
    english6: "satisfactory",
    english7: "park",
    english8: "seat",
    english9: "airconditioner",
    english10: "train",
  },
  {
    day: 33,

    nihongo1: "だす",
    nihongo2: "やっと",
    nihongo3: "かいもの",
    nihongo4: "は",
    nihongo5: "はし",
    nihongo6: "けいさつしょ",
    nihongo7: "しゃくしょ",
    nihongo8: "どうぶつえん",
    nihongo9: "たいいくかん",
    nihongo10: "たいしかん",

    english1: "to take out/ to put out",
    english2: "finally",
    english3: "shopping",
    english4: "teeth",
    english5: "chopsticks",
    english6: "police station",
    english7: "city hall",
    english8: "zoo",
    english9: "gym",
    english10: "embassy",
  },
  {
    day: 34,

    nihongo1: "げんご",
    nihongo2: "ふく",
    nihongo3: "うんてん",
    nihongo4: "くび",
    nihongo5: "ほうこく",
    nihongo6: "すむ",
    nihongo7: "すう",
    nihongo8: "はなや",
    nihongo9: "いりぐち",
    nihongo10: "ますぐ",

    english1: "language",
    english2: "clothes",
    english3: "driving",
    english4: "neck",
    english5: "announcement",
    english6: "to live",
    english7: "to smoke",
    english8: "flower shop",
    english9: "entrance",
    english10: "straight",
  },
  {
    day: 35,

    nihongo1: "さそう",
    nihongo2: "けす",
    nihongo3: "こくばん",
    nihongo4: "こわす",
    nihongo5: "ぬすむ",
    nihongo6: "べんごし",
    nihongo7: "てにん",
    nihongo8: "びようし",
    nihongo9: "きようし",
    nihongo10: "けいさつ",

    english1: "to invite",
    english2: "to turn off / to erase",
    english3: "blackboard",
    english4: "to break / to destroy",
    english5: "to steal",
    english6: "lawyer",
    english7: "cashier / clerk",
    english8: "hairdresser",
    english9: "teacher",
    english10: "police",
  },
  {
    day: 36,

    nihongo1: "いたみ",
    nihongo2: "きりつ",
    nihongo3: "きめる",
    nihongo4: "さいふ",
    nihongo5: "えいがかん",
    nihongo6: "ちょう",
    nihongo7: "にぎやか",
    nihongo8: "てわ",
    nihongo9: "じょぶ",
    nihongo10: "りっぱ",

    english1: "pain",
    english2: "discipline",
    english3: "to decide",
    english4: "wallet",
    english5: "movie theater",
    english6: "butterfly",
    english7: "busy / lively (busy city)",
    english8: "help / look after",
    english9: "strong",
    english10: "respectable",
  },
  {
    day: 37,

    nihongo1: "かがみ",
    nihongo2: "のぞく",
    nihongo3: "せいかく",
    nihongo4: "さいきｎ",
    nihongo5: "だれか",
    nihongo6: "みち",
    nihongo7: "みかん",
    nihongo8: "なし",
    nihongo9: "ほしゅてき",
    nihongo10: "ひま",

    english1: "mirror",
    english2: "to peek",
    english3: "personality",
    english4: "lately",
    english5: "someone / somebody",
    english6: "street / road",
    english7: "orange",
    english8: "pear",
    english9: "conservative",
    english10: "free time",
  },
  {
    day: 38,

    nihongo1: "もうふ",
    nihongo2: "ささえる",
    nihongo3: "かんじる",
    nihongo4: "かた",
    nihongo5: "あし",
    nihongo6: "ちゅうもん　する",
    nihongo7: "かいけい",
    nihongo8: "べつ　べつ",
    nihongo9: "くだもの",
    nihongo10: "えがく",

    english1: "blanket",
    english2: "to support",
    english3: "to feel",
    english4: "shoulder",
    english5: "feet / leg",
    english6: "to order",
    english7: "payment",
    english8: "individually / separately",
    english9: "fruits",
    english10: "to draw (advance drawing)",
  },
  {
    day: 39,

    nihongo1: "はなれる",
    nihongo2: "にゅうがく",
    nihongo3: "そつぎょう",
    nihongo4: "ふるさと",
    nihongo5: "ほめる",
    nihongo6: "かいす",
    nihongo7: "こいい",
    nihongo8: "うすい",
    nihongo9: "くうこう",
    nihongo10: "みがく",

    english1: "to leave",
    english2: "admission",
    english3: "graduation",
    english4: "hometown",
    english5: "to praise",
    english6: "to return",
    english7: "thick",
    english8: "thin",
    english9: "airport",
    english10: "to brush",
  },
  {
    day: 40,

    nihongo1: "せいふ",
    nihongo2: "いたい",
    nihongo3: "みみ",
    nihongo4: "めがね",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "government",
    english2: "painful",
    english3: "ear",
    english4: "eyeglasses",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
  {
    day: 41,

    nihongo1: "",
    nihongo2: "",
    nihongo3: "",
    nihongo4: "",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "",
    english2: "",
    english3: "",
    english4: "",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
  {
    day: 42,

    nihongo1: "",
    nihongo2: "",
    nihongo3: "",
    nihongo4: "",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "",
    english2: "",
    english3: "",
    english4: "",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
  {
    day: 43,

    nihongo1: "",
    nihongo2: "",
    nihongo3: "",
    nihongo4: "",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "",
    english2: "",
    english3: "",
    english4: "",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
  {
    day: 44,

    nihongo1: "",
    nihongo2: "",
    nihongo3: "",
    nihongo4: "",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "",
    english2: "",
    english3: "",
    english4: "",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
  {
    day: 45,

    nihongo1: "",
    nihongo2: "",
    nihongo3: "",
    nihongo4: "",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "",
    english2: "",
    english3: "",
    english4: "",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
  {
    day: 46,

    nihongo1: "",
    nihongo2: "",
    nihongo3: "",
    nihongo4: "",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "",
    english2: "",
    english3: "",
    english4: "",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
  {
    day: 47,

    nihongo1: "",
    nihongo2: "",
    nihongo3: "",
    nihongo4: "",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "",
    english2: "",
    english3: "",
    english4: "",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
  {
    day: 48,

    nihongo1: "",
    nihongo2: "",
    nihongo3: "",
    nihongo4: "",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "",
    english2: "",
    english3: "",
    english4: "",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
  {
    day: 49,

    nihongo1: "",
    nihongo2: "",
    nihongo3: "",
    nihongo4: "",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "",
    english2: "",
    english3: "",
    english4: "",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
  {
    day: 50,

    nihongo1: "",
    nihongo2: "",
    nihongo3: "",
    nihongo4: "",
    nihongo5: "",
    nihongo6: "",
    nihongo7: "",
    nihongo8: "",
    nihongo9: "",
    nihongo10: "",

    english1: "",
    english2: "",
    english3: "",
    english4: "",
    english5: "",
    english6: "",
    english7: "",
    english8: "",
    english9: "",
    english10: "",
  },
];

export default card;
